config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'link'    => 'static_pages#link'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <small>
      管理者 小野村 一馬
    </small>
    <nav>
      <ul>
        <a class="facebook" href="https://www.facebook.com/sharer/sharer.php?u=https://football-com-soccer.herokuapp.com/" target="_blank">Facebook</a>
        <a class="twitter" href="https://twitter.com/intent/tweet?text=サッカー情報シェアサイト！！&url=https://football-com-soccer.herokuapp.com/" target="_blank">twitter</a>
        <a class="line" href="http://line.me/R/msg/text/?https://football-com-soccer.herokuapp.com/" target="_blank">LINE</a>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "FOOTBALL.com", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path, id: "menu"%></li>
        <li><%= link_to "このサイトについて", help_path, id: "menu"%></li>
        <li><%= link_to "お問い合わせ", contact_path, id: "menu"%></li>
        <% if logged_in? %>
          <li><%= link_to "おすすめリンク集", link_path, id: "menu"%></li>
          <li><%= link_to "ユーザー一覧", users_path, id: "menu"%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown", id="menu">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user , id: "menu2"%></li>
              <li><%= link_to "設定", edit_user_path(current_user), id: "menu2" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete, id: "menu2" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path, id: "menu"%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application',
                             'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>